# Generated by Django 5.0.2 on 2025-04-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeranalysis',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
    ]
